### ISSUE TITLE
Cannot read property 'addIceCandidate' of undefined

### ISSUE THREAD

**Issue by dima-dmytruk23** [lnogueir/webrtc-socketio#1]
When I connect the second user I get the following logs.
**The first user has:**
```
Stream found
main.js:15 Ready
main.js:47 PeerConnection created
main.js:52 Send offer
main.js:73 Local description set
main.js:79 8 ICE candidate
```

**Second user:**
```
Stream found
main.js:10 Data received:  {sid: "4ydg5KtKA_Fxl81SAAAJ"}
main.js:10 Data received:  {type: "candidate", candidate: {…}, sid: "4ydg5KtKA_Fxl81SAAAJ"}
main.js:109 Uncaught TypeError: Cannot read property 'addIceCandidate' of undefined
    at handleSignalingData (main.js:109)
    at Socket.<anonymous> (main.js:11)
    at Socket../node_modules/component-emitter/index.js.Emitter.emit (socket.io.js:1761)
    at Socket.emitEvent (socket.io.js:1160)
    at Socket.onevent (socket.io.js:1134)
    at Socket.onpacket (socket.io.js:1086)
    at Manager../node_modules/component-emitter/index.js.Emitter.emit (socket.io.js:1761)
    at Manager.ondecoded (socket.io.js:526)
    at Decoder../node_modules/component-emitter/index.js.Emitter.emit (socket.io.js:1761)
    at Decoder.add (socket.io.js:5500)
```

https://github.com/lnogueir/webrtc-socketio/blob/aec989350251955ecb6b3b9d767916adca053b42/main.js#L109

**Comment by lnogueir** [comment]
Ok, I think this is because you are receiving candidates before you have finished handling the offer, so when you try to addICECandidate, peers[sid] is still undefined. 

I didn't have this issue locally, but I believe the solution is to have a list of pending ice candidates (those that arrive before setting remote offer), and then once we set remote offer fine, then we add all those pending candidates.

Thanks for letting me know, I'll work on a fix for that and get back to you later today.

**Comment by lnogueir** [comment]
Hey, so I have just added a pendingCandidates object to make sure we don't add candidates when peer[sid] is potentially undefined.

I also realized the code wasn't working on chrome because I was using spread operator on an RTCSessionDescription object, firefox seems to accept it, but chrome not.

Didn't test it thoroughly, so let me know if you still have problems connecting.
